#!/usr/bin/env python3
"""Train a non-aligned clean-reference effect-family detector.

The user reference is a set-level timbre profile, never an aligned performance.
Training episodes deliberately pair each query with untreated audio from another
performance group. Only archived real recordings are used; no effect audio is
rendered or generated by this experiment.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
import time
from pathlib import Path

import numpy as np
import onnx
import onnxruntime
import torch

from data import (
    Item,
    add_rir_reverb,
    discover,
    discover_aachen_rirs,
    discover_guitar_effect_chains,
    discover_idmt_guitar,
    discover_remfx_1_1,
    discover_tonetwist_big_muff_nc,
    eligible_clean,
    guitar_effect_chain_is_clean,
)
from detect import calibrated, fit_platt, gate_feasibility, metrics, thresholds
from evaluate import expected as external_expected
from model import EMBEDDING, FRAMES, LABELS, MELS, Detector, frontend, parameters
from reference import (
    EncoderExport,
    audio_windows,
    cache_features,
    encode_items,
    real_only_split,
    reference_domain,
    target_device,
)


ROOT = Path(__file__).resolve().parents[1]
SEED = 20260828
PHYSICS_LAGS = (2, 4, 6, 8, 10, 13, 17, 22, 30, 40, 55, 75)
PHYSICS = len(PHYSICS_LAGS) * 2 + 4 + 5 + 16 + 16


class RelativeHead(torch.nn.Module):
    """Classify effect-family changes relative to an unordered Clean set."""

    def __init__(self, input_dimension: int) -> None:
        super().__init__()
        self.network = torch.nn.Sequential(
            torch.nn.Linear(input_dimension, EMBEDDING),
            torch.nn.LayerNorm(EMBEDDING),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.20),
            torch.nn.Linear(EMBEDDING, 64),
            torch.nn.ReLU(),
            torch.nn.Linear(64, len(LABELS)),
        )

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        return self.network(value)


def checkpoint_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def encoded_cache_path(
    root: Path, split: str, checkpoint_hash: str, feature_path: Path
) -> Path:
    dataset_hash = feature_path.stem.split("-")[1]
    return root / f"{split}-relative-{checkpoint_hash[:12]}-{dataset_hash}.npz"


def cached_encoding(
    model: Detector,
    items: list[Item],
    feature_paths: tuple[Path, Path],
    split: str,
    root: Path,
    checkpoint_hash: str,
    batch: int,
    device: torch.device,
) -> dict[str, np.ndarray]:
    path = encoded_cache_path(root, split, checkpoint_hash, feature_paths[0])
    if path.exists():
        payload = np.load(path)
        if payload["embedding"].shape == (len(items), EMBEDDING):
            value = {key: payload[key] for key in payload.files}
            if "physics" not in value:
                value["physics"] = cached_physics(feature_paths[0])
                np.savez_compressed(path, **value)
            return value
    value = encode_items(model, items, feature_paths, batch, device)
    value["group"] = np.asarray([item.source.group for item in items])
    value["physics"] = cached_physics(feature_paths[0])
    np.savez_compressed(path, **value)
    return value


def physics_features(value: np.ndarray) -> np.ndarray:
    """Extract deterministic family-oriented statistics from normalized log-Mel."""

    mel = np.asarray(value, dtype=np.float32)
    if mel.ndim == 4:
        mel = mel[:, 0]
    if mel.ndim != 3 or mel.shape[1:] != (MELS, FRAMES):
        raise ValueError(f"expected [N,{MELS},{FRAMES}], got {mel.shape}")
    envelope = mel.mean(axis=1)
    envelope = envelope - envelope.mean(axis=1, keepdims=True)
    envelope = envelope / (envelope.std(axis=1, keepdims=True) + 1.0e-5)
    correlations, differences = [], []
    for lag in PHYSICS_LAGS:
        correlations.append((envelope[:, :-lag] * envelope[:, lag:]).mean(axis=1))
        differences.append(np.abs(envelope[:, :-lag] - envelope[:, lag:]).mean(axis=1))
    delta = np.diff(mel, axis=2)
    flux = np.stack(
        (
            np.abs(delta).mean(axis=(1, 2)),
            np.maximum(delta, 0).mean(axis=(1, 2)),
            np.maximum(-delta, 0).mean(axis=(1, 2)),
            delta.std(axis=(1, 2)),
        ),
        axis=1,
    )
    envelope_stats = np.stack(
        (
            envelope.std(axis=1),
            envelope.max(axis=1),
            envelope.min(axis=1),
            np.abs(np.diff(envelope, axis=1)).mean(axis=1),
            np.percentile(envelope, 90, axis=1) - np.percentile(envelope, 10, axis=1),
        ),
        axis=1,
    )
    bands = mel.reshape(len(mel), 8, MELS // 8, FRAMES)
    band_mean = bands.mean(axis=(2, 3))
    band_deviation = bands.std(axis=(2, 3))
    trimmed = mel[:, :, : (FRAMES // 8) * 8]
    chunks = trimmed.reshape(len(mel), MELS, 8, FRAMES // 8)
    chunk_mean = chunks.mean(axis=(1, 3))
    chunk_deviation = chunks.std(axis=(1, 3))
    result = np.concatenate(
        (
            np.stack(correlations, axis=1),
            np.stack(differences, axis=1),
            flux,
            envelope_stats,
            band_mean,
            band_deviation,
            chunk_mean,
            chunk_deviation,
        ),
        axis=1,
    ).astype(np.float32)
    if result.shape[1] != PHYSICS:
        raise RuntimeError(f"physics feature contract drifted: {result.shape[1]} != {PHYSICS}")
    return result


def cached_physics(feature_path: Path) -> np.ndarray:
    path = feature_path.with_name(feature_path.stem + "-physics-v1.npy")
    features = np.load(feature_path, mmap_mode="r")
    if path.exists():
        result = np.load(path, mmap_mode="r")
        if result.shape == (len(features), PHYSICS):
            return np.asarray(result)
    result = np.lib.format.open_memmap(
        path, mode="w+", dtype=np.float32, shape=(len(features), PHYSICS)
    )
    for start in range(0, len(features), 512):
        result[start : start + 512] = physics_features(features[start : start + 512])
    result.flush()
    return np.asarray(result)


def representation(encoded: dict[str, np.ndarray], mode: str) -> np.ndarray:
    if mode == "embedding":
        return encoded["embedding"].astype(np.float32)
    if mode == "embedding-logits":
        return np.concatenate(
            (encoded["embedding"], encoded["base_logits"]), axis=1
        ).astype(np.float32)
    if mode == "physics":
        return encoded["physics"].astype(np.float32)
    if mode == "hybrid":
        return np.concatenate((encoded["embedding"], encoded["physics"]), axis=1).astype(np.float32)
    raise ValueError(f"unknown feature mode: {mode}")


def actual_clean_mask(items: list[Item], clean_paths: set[Path]) -> np.ndarray:
    return np.asarray(
        [
            (
                item.source.path.resolve() in clean_paths
                and eligible_clean(item.source)
                and item.effect_ir is None
            )
            or (
                item.source.domain.startswith("idmt-setting-")
                and item.source.path.parent.name == "NoFX"
            )
            for item in items
        ],
        dtype=bool,
    )


def episode_features(
    encoded: dict[str, np.ndarray],
    reference_mask: np.ndarray,
    mode: str,
    seed: int,
    repeats: int,
    minimum_references: int = 1,
    maximum_references: int = 4,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
    """Build fixed episodes whose reference groups never match the query."""

    rng = np.random.default_rng(seed)
    embeddings = representation(encoded, mode)
    labels = encoded["labels"].astype(np.float32)
    domains = encoded["domain"].astype(str)
    groups = encoded["group"].astype(str)
    clean_indices = np.flatnonzero(reference_mask)
    by_domain = {
        domain: clean_indices[domains[clean_indices] == domain]
        for domain in sorted(set(domains[clean_indices]))
    }
    features: list[np.ndarray] = []
    targets: list[np.ndarray] = []
    query_indices: list[int] = []
    same_group = 0
    sizes: list[int] = []
    for _ in range(repeats):
        for query_index in range(len(embeddings)):
            candidates = by_domain.get(domains[query_index], clean_indices)
            candidates = candidates[groups[candidates] != groups[query_index]]
            if not len(candidates):
                candidates = clean_indices[groups[clean_indices] != groups[query_index]]
            if not len(candidates):
                raise RuntimeError(f"no non-aligned Clean reference for {groups[query_index]}")
            size = int(rng.integers(minimum_references, maximum_references + 1))
            selected = rng.choice(candidates, size=size, replace=len(candidates) < size)
            same_group += int(np.any(groups[selected] == groups[query_index]))
            reference = embeddings[selected]
            mean = reference.mean(axis=0)
            deviation = reference.std(axis=0) + 1.0e-4
            query = embeddings[query_index]
            features.append(
                np.concatenate((query, mean, query - mean, np.abs(query - mean), deviation))
            )
            targets.append(labels[query_index])
            query_indices.append(query_index)
            sizes.append(size)
    audit = {
        "episodes": len(features),
        "same_group_references": same_group,
        "non_aligned_fraction": float(1.0 - same_group / max(len(features), 1)),
        "reference_set_size_min": min(sizes),
        "reference_set_size_max": max(sizes),
        "reference_set_size_mean": float(np.mean(sizes)),
    }
    return (
        np.stack(features).astype(np.float32),
        np.stack(targets).astype(np.float32),
        np.asarray(query_indices, dtype=np.int64),
        audit,
    )


def train_head(
    head: RelativeHead,
    train_values: tuple[np.ndarray, np.ndarray],
    valid_values: tuple[np.ndarray, np.ndarray],
    output: Path,
    device: torch.device,
    epochs: int,
    patience: int,
    learning_rate: float,
) -> tuple[int, float, float]:
    train_x = torch.from_numpy(train_values[0]).to(device)
    train_y = torch.from_numpy(train_values[1]).to(device)
    valid_x = torch.from_numpy(valid_values[0]).to(device)
    valid_y = torch.from_numpy(valid_values[1]).to(device)
    positives = train_values[1].sum(axis=0)
    weight = torch.tensor(
        np.clip((len(train_values[1]) - positives) / np.maximum(positives, 1), 1, 8),
        dtype=torch.float32,
        device=device,
    )
    loss_fn = torch.nn.BCEWithLogitsLoss(pos_weight=weight)
    optimizer = torch.optim.AdamW(
        head.parameters(), lr=learning_rate, weight_decay=1.0e-4
    )
    best, stale, completed = float("inf"), 0, 0
    started = time.perf_counter()
    for epoch in range(epochs):
        head.train()
        order = torch.randperm(len(train_x), device=device)
        for start in range(0, len(order), 256):
            selected = order[start : start + 256]
            optimizer.zero_grad(set_to_none=True)
            loss = loss_fn(head(train_x[selected]), train_y[selected])
            loss.backward()
            torch.nn.utils.clip_grad_norm_(head.parameters(), 5.0)
            optimizer.step()
        head.eval()
        with torch.no_grad():
            value = float(loss_fn(head(valid_x), valid_y).cpu())
        completed = epoch + 1
        print("relative_epoch", completed, "valid_loss", value)
        if value < best - 1.0e-5:
            best, stale = value, 0
            torch.save(head.state_dict(), output / "relative-head.pt")
        else:
            stale += 1
            if stale >= patience:
                break
    head.load_state_dict(
        torch.load(output / "relative-head.pt", map_location=device, weights_only=True)
    )
    return completed, best, time.perf_counter() - started


def infer(head: RelativeHead, features: np.ndarray, device: torch.device) -> np.ndarray:
    result = []
    head.eval()
    with torch.no_grad():
        for start in range(0, len(features), 512):
            result.append(head(torch.from_numpy(features[start : start + 512]).to(device)).cpu().numpy())
    return np.concatenate(result)


def domain_metrics(
    expected: np.ndarray, probabilities: np.ndarray, threshold: np.ndarray
) -> dict:
    """Avoid treating absent effect classes as perfect domain-level F1."""

    result = metrics(expected, probabilities, threshold)
    supported = []
    positive_counts = {}
    negative_false_positive_rate = {}
    for index, label in enumerate(LABELS):
        positives = int((expected[:, index] > 0.5).sum())
        positive_counts[label] = positives
        negatives = expected[:, index] <= 0.5
        negative_false_positive_rate[label] = (
            float((probabilities[negatives, index] >= threshold[index]).mean())
            if negatives.any()
            else None
        )
        if positives:
            supported.append(result[label]["f1"])
        else:
            result[label] = {
                "precision": None,
                "recall": None,
                "f1": None,
                "note": "not applicable: this domain contains no positive examples",
            }
    result["macro_f1"] = float(np.mean(supported)) if supported else None
    result["positive_counts"] = positive_counts
    result["negative_false_positive_rate"] = negative_false_positive_rate
    return result


def fused_with_profile(
    embedding: np.ndarray, mean: np.ndarray, deviation: np.ndarray
) -> np.ndarray:
    means = np.repeat(mean[None], len(embedding), axis=0)
    deviations = np.repeat(deviation[None], len(embedding), axis=0)
    return np.concatenate(
        (embedding, means, embedding - means, np.abs(embedding - means), deviations), axis=1
    ).astype(np.float32)


def encode_relative_windows(
    model: Detector, path: Path, mode: str, device: torch.device
) -> tuple[np.ndarray, np.ndarray]:
    waveform = torch.from_numpy(audio_windows(path))
    values, blind_values = [], []
    model.eval()
    with torch.no_grad():
        for start in range(0, len(waveform), 16):
            mel = frontend(waveform[start : start + 16])
            components = []
            embedding = model.encode(mel.to(device))
            blind_logits = model.head(embedding)
            if mode in {"embedding", "embedding-logits", "hybrid"}:
                components.append(embedding.cpu().numpy())
                if mode == "embedding-logits":
                    components.append(blind_logits.cpu().numpy())
            if mode in {"physics", "hybrid"}:
                components.append(physics_features(mel.numpy()))
            values.append(np.concatenate(components, axis=1))
            blind_values.append(blind_logits.cpu().numpy())
    return (
        np.concatenate(values).astype(np.float32),
        np.concatenate(blind_values).astype(np.float32),
    )


def reference_window_count(seconds: int, total: int) -> int:
    # Five-second windows with a 2.5-second hop.
    hop_seconds = 2.5
    return min(total, max(1, 1 + int(max(0, seconds - 5) / hop_seconds)))


def external_report(
    model: Detector,
    head: RelativeHead,
    reference: Path,
    directory: Path,
    scales: np.ndarray,
    biases: np.ndarray,
    seconds: int,
    mode: str,
    device: torch.device,
    blind_calibration: tuple[np.ndarray, np.ndarray, np.ndarray] | None = None,
    delay_route: str = "blind",
    reverb_route: str = "or",
    external_delay_floor: float = 0.55,
    external_reverb_floor: float = 0.59,
) -> tuple[dict, dict[str, np.ndarray]]:
    started = time.perf_counter()
    reference_embedding, reference_blind_logits = encode_relative_windows(
        model, reference, mode, device
    )
    count = reference_window_count(seconds, len(reference_embedding))
    selected = reference_embedding[:count]
    mean = selected.mean(axis=0)
    deviation = selected.std(axis=0) + 1.0e-4
    encode_seconds = time.perf_counter() - started
    clean_logits = infer(head, fused_with_profile(selected, mean, deviation), device)
    clean_probabilities = calibrated(clean_logits, scales, biases)
    # This is negative-support calibration only: no weights are updated and no
    # query labels or query audio influence the threshold.
    user_floor = np.asarray(
        [0.05, external_delay_floor, external_reverb_floor], dtype=np.float32
    )
    user_threshold = np.minimum(
        np.maximum(clean_probabilities.max(axis=0) + 0.02, user_floor), 0.95
    )
    # Five-second windows use a 2.5-second hop. Skipping one window ensures the
    # first held-out Clean query starts where the final reference window ends.
    held_out_embedding = reference_embedding[count + 1 :]
    held_out_blind_logits = reference_blind_logits[count + 1 :]
    if len(held_out_embedding):
        held_out_pair = calibrated(
            infer(head, fused_with_profile(held_out_embedding, mean, deviation), device),
            scales,
            biases,
        ) >= user_threshold
        held_out_prediction = held_out_pair.copy()
        if blind_calibration is not None:
            blind_scales, blind_biases, blind_threshold = blind_calibration
            held_out_blind = calibrated(
                held_out_blind_logits, blind_scales, blind_biases
            ) >= blind_threshold
            held_out_prediction[:, 0] = np.logical_or(
                held_out_pair[:, 0], held_out_blind[:, 0]
            )
            held_out_prediction[:, 1] = (
                held_out_pair[:, 1]
                if delay_route == "pair"
                else held_out_blind[:, 1]
            )
            held_out_prediction[:, 2] = (
                held_out_pair[:, 2]
                if reverb_route == "pair"
                else np.logical_or(held_out_pair[:, 2], held_out_blind[:, 2])
            )
        clean_false_positive = float(held_out_prediction.any(axis=1).mean())
    else:
        clean_false_positive = None
    rows, truths, predictions, pair_predictions = [], [], [], []
    query_started = time.perf_counter()
    for path in sorted(directory.glob("*.wav")):
        if path.resolve() == reference.resolve():
            continue
        embedding, blind_logits = encode_relative_windows(model, path, mode, device)
        logits = infer(head, fused_with_profile(embedding, mean, deviation), device)
        probabilities = calibrated(logits, scales, biases)
        strongest = min(2, len(probabilities))
        top2 = np.partition(probabilities, len(probabilities) - strongest, axis=0)[-strongest:].mean(axis=0)
        truth = external_expected(path)
        pair_predicted = top2 >= user_threshold
        predicted = pair_predicted.copy()
        blind_top2 = None
        blind_predicted = None
        if blind_calibration is not None:
            blind_scales, blind_biases, blind_threshold = blind_calibration
            blind_probabilities = calibrated(
                blind_logits, blind_scales, blind_biases
            )
            blind_top2 = np.partition(
                blind_probabilities, len(blind_probabilities) - strongest, axis=0
            )[-strongest:].mean(axis=0)
            blind_predicted = blind_top2 >= blind_threshold
            # Drive keeps the blind rescue path. Delay and Reverb can instead
            # be routed through the user-conditioned pair head when a clean
            # reference removes enough capture-domain ambiguity.
            predicted[1] = (
                pair_predicted[1]
                if delay_route == "pair"
                else blind_predicted[1]
            )
            predicted[0] = np.logical_or(pair_predicted[0], blind_predicted[0])
            predicted[2] = (
                pair_predicted[2]
                if reverb_route == "pair"
                else np.logical_or(pair_predicted[2], blind_predicted[2])
            )
        truths.append(truth)
        predictions.append(predicted)
        pair_predictions.append(pair_predicted)
        rows.append(
            {
                "file": path.name,
                "expected": [LABELS[index] for index in np.flatnonzero(truth)],
                "predicted": [LABELS[index] for index in np.flatnonzero(predicted)],
                "pair_predicted": [
                    LABELS[index] for index in np.flatnonzero(pair_predicted)
                ],
                "blind_predicted": [
                    LABELS[index] for index in np.flatnonzero(blind_predicted)
                ] if blind_predicted is not None else None,
                "top2_mean": dict(zip(LABELS, map(float, top2))),
                "blind_top2_mean": dict(zip(LABELS, map(float, blind_top2)))
                if blind_top2 is not None else None,
            }
        )
    truth = np.stack(truths)
    predicted = np.stack(predictions)
    pair_predicted = np.stack(pair_predictions)
    scored = metrics(
        truth, predicted.astype(np.float32), np.full(len(LABELS), 0.5, dtype=np.float32)
    )
    scored["clean_false_positive"] = clean_false_positive
    return {
        "role": "external-development with temporally held-out Clean windows",
        "reference": str(reference.resolve()),
        "reference_requested_seconds": seconds,
        "reference_windows": count,
        "held_out_clean_windows": int(len(held_out_embedding)),
        "held_out_clean_relation": (
            "same recording and device, non-overlapping with reference; not an independent recording"
        ),
        "reference_encode_seconds": encode_seconds,
        "gradient_updates": 0,
        "threshold": dict(zip(LABELS, map(float, user_threshold))),
        "query_files": len(rows),
        "query_seconds": time.perf_counter() - query_started,
        "clean_false_positive_measurable": bool(len(held_out_embedding)),
        "clean_false_positive": clean_false_positive,
        "metrics": scored,
        "pair_metrics": metrics(
            truth,
            pair_predicted.astype(np.float32),
            np.full(len(LABELS), 0.5, dtype=np.float32),
        ),
        "fusion": (
            f"{delay_route} Delay; blind OR non-aligned pair for Drive; "
            f"{reverb_route} Reverb"
            if blind_calibration is not None
            else None
        ),
        "results": rows,
    }, {"mean": mean.astype(np.float32), "standard_deviation": deviation.astype(np.float32)}


def quality_gate(
    calibrate_report: dict, test_report: dict, domain_reports: dict, external: dict
) -> dict:
    failures = []
    for split, report in (("calibration", calibrate_report), ("test", test_report)):
        if report["clean_false_positive"] > 0.05:
            failures.append(f"{split} Clean false-positive rate exceeds 5%")
        for label in LABELS:
            if report[label]["recall"] < 0.80:
                failures.append(f"{split} {label} recall is below 80%")
    for domain, report in domain_reports.items():
        if report["clean_false_positive"] > 0.05:
            failures.append(f"{domain} Clean false-positive rate exceeds 5%")
        for label in LABELS:
            recall = report[label]["recall"]
            if recall is not None and recall < 0.80:
                failures.append(f"{domain} {label} recall is below 80%")
    if not external["clean_false_positive_measurable"]:
        failures.append("external user-domain Clean FP is not independently measurable")
    elif external["clean_false_positive"] > 0.05:
        failures.append("external user-domain temporally held-out Clean FP exceeds 5%")
    for label in LABELS:
        if external["metrics"][label]["recall"] < 0.80:
            failures.append(f"external {label} recall is below 80%")
        if external["metrics"][label]["precision"] < 0.50:
            failures.append(f"external {label} precision is below 50%")
    return {
        "passed": not failures,
        "requirements": {
            "clean_false_positive_max": 0.05,
            "per_class_recall_min": 0.80,
            "external_per_class_precision_min": 0.50,
        },
        "failures": failures,
    }


def export(model: Detector, head: RelativeHead, input_dimension: int, output: Path) -> dict:
    model = model.cpu().eval()
    head = head.cpu().eval()
    mel = torch.randn(1, 1, MELS, FRAMES)
    fused = torch.randn(1, input_dimension)
    encoder_path = output / "relative-encoder.onnx"
    head_path = output / "relative-head.onnx"
    encoder = EncoderExport(model).eval()
    torch.onnx.export(
        encoder, mel, encoder_path, input_names=["mel"],
        output_names=["embedding", "unused_blind_logits"], opset_version=17, dynamo=False,
    )
    torch.onnx.export(
        head, fused, head_path, input_names=["relative_features"],
        output_names=["logits"], opset_version=17, dynamo=False,
    )
    onnx.checker.check_model(onnx.load(encoder_path))
    onnx.checker.check_model(onnx.load(head_path))
    encoder_session = onnxruntime.InferenceSession(str(encoder_path))
    head_session = onnxruntime.InferenceSession(str(head_path))
    expected_encoder = encoder(mel)[0].detach().numpy().copy()
    actual_encoder = encoder_session.run(["embedding"], {"mel": mel.numpy()})[0].copy()
    expected_head = head(fused).detach().numpy().copy()
    actual_head = head_session.run(["logits"], {"relative_features": fused.numpy()})[0].copy()
    return {
        "encoder_max_absolute_difference": float(np.max(np.abs(expected_encoder - actual_encoder))),
        "head_max_absolute_difference": float(np.max(np.abs(expected_head - actual_head))),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=Path, default=ROOT / "data" / "corpus")
    parser.add_argument(
        "--reference", type=Path, default=Path.home() / "Downloads/test/clean.wav"
    )
    parser.add_argument("--external", type=Path, default=Path.home() / "Downloads/test")
    parser.add_argument("--output", type=Path, default=ROOT / "train" / "runs" / "relative-real-v1")
    parser.add_argument("--checkpoint", type=Path, default=ROOT / "train" / "runs" / "clean-reference-real-v1" / "backbone.pt")
    parser.add_argument(
        "--stem-stride",
        type=int,
        choices=(1, 2),
        default=2,
        help="must match the architecture used to train --checkpoint",
    )
    parser.add_argument("--cache", type=Path, default=ROOT / "train" / "cache" / "clean-reference-real-v1")
    parser.add_argument(
        "--idmt-guitar",
        action="store_true",
        help="add the audited non-commercial IDMT guitar subset",
    )
    parser.add_argument(
        "--remfx-1-1",
        action="store_true",
        help="add audited CC-NC RemFX wet/dry pairs to training only",
    )
    parser.add_argument(
        "--guitar-effects-chains",
        action="store_true",
        help="include the CC-BY-4.0 DAFx25 archived five-effect-chain dataset",
    )
    parser.add_argument(
        "--aachen-rir",
        action="store_true",
        help="add CC-BY-4.0 measured-room reverb examples by ephemeral convolution",
    )
    parser.add_argument(
        "--tonetwist-big-muff-nc",
        action="store_true",
        help="include audited CC-BY-NC ToneTwisT Big Muff pairs for research only",
    )
    parser.add_argument("--tonetwist-train-repeats", type=int, default=8)
    parser.add_argument(
        "--idmt-manifest",
        type=Path,
        default=ROOT / "train" / "runs" / "idmt-guitar-manifest.json",
    )
    parser.add_argument(
        "--blind-calibration",
        type=Path,
        help="enable frozen-blind/pair fusion with this calibration file",
    )
    parser.add_argument(
        "--blind-delay-threshold",
        type=float,
        help="optional auditable override for the frozen blind Delay threshold",
    )
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--patience", type=int, default=12)
    parser.add_argument("--train-episodes", type=int, default=2)
    parser.add_argument("--initial-head", type=Path)
    parser.add_argument(
        "--warm-start-head",
        type=Path,
        help="initialize the pair head from a checkpoint and continue fitting",
    )
    parser.add_argument("--head-learning-rate", type=float, default=8.0e-4)
    parser.add_argument(
        "--calibration-clean-fp-target", type=float, default=0.05
    )
    parser.add_argument(
        "--delay-route",
        choices=("blind", "pair"),
        default="blind",
        help="route Delay through the frozen blind branch or clean-reference pair head",
    )
    parser.add_argument(
        "--reverb-route",
        choices=("or", "pair"),
        default="or",
        help="route Reverb through pair only or pair/blind OR fusion",
    )
    parser.add_argument(
        "--external-delay-floor",
        type=float,
        default=0.55,
        help="minimum clean-conditioned Delay probability threshold",
    )
    parser.add_argument(
        "--external-reverb-floor",
        type=float,
        default=0.59,
        help="minimum clean-conditioned Reverb probability threshold",
    )
    parser.add_argument(
        "--reference-seconds", type=int, choices=(5, 10, 20), default=10
    )
    parser.add_argument("--experiment")
    parser.add_argument("--hypothesis")
    parser.add_argument(
        "--feature-mode",
        choices=("embedding", "embedding-logits", "physics", "hybrid"),
        default="embedding",
    )
    parser.add_argument("--seed", type=int, default=SEED)
    args = parser.parse_args()
    if args.initial_head and args.warm_start_head:
        parser.error("--initial-head and --warm-start-head are mutually exclusive")
    if args.head_learning_rate <= 0.0:
        parser.error("--head-learning-rate must be positive")
    if args.blind_delay_threshold is not None and not 0.0 <= args.blind_delay_threshold <= 1.0:
        parser.error("--blind-delay-threshold must be between 0 and 1")
    if not 0.0 <= args.external_delay_floor <= 0.95:
        parser.error("--external-delay-floor must be between 0 and 0.95")
    if not 0.0 <= args.external_reverb_floor <= 0.95:
        parser.error("--external-reverb-floor must be between 0 and 0.95")
    experiment = args.experiment or f"relative-{args.feature_mode}-real-v1"
    hypothesis = args.hypothesis or (
        f"Non-aligned Clean-reference {args.feature_mode} features improve cross-performance "
        "effect-family detection without user fine-tuning or generated effect audio."
    )
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    args.output.mkdir(parents=True, exist_ok=True)
    if not args.reference.exists():
        parser.error(f"missing user reference: {args.reference}")
    if not args.checkpoint.exists():
        parser.error(f"missing frozen encoder checkpoint: {args.checkpoint}")

    clean, anchors = discover(args.data)
    parts = real_only_split(clean, anchors)
    chain_items = {name: [] for name in parts}
    if args.guitar_effects_chains:
        chain_items = discover_guitar_effect_chains(args.data / "guitar-effects-chains")
        if not any(chain_items.values()):
            parser.error("--guitar-effects-chains found no archived audio")
        for name in parts:
            parts[name].extend(chain_items[name])
    if args.aachen_rir:
        rirs = discover_aachen_rirs(args.data / "aachen-chapel-rir")
        rir_clean_paths = {source.path.resolve() for source in clean if eligible_clean(source)}
        rir_clean_paths.update(
            item.source.path.resolve()
            for items in chain_items.values()
            for item in items
            if guitar_effect_chain_is_clean(item.source)
        )
        parts = add_rir_reverb(parts, rirs, rir_clean_paths)
    tonetwist_items = {name: [] for name in parts}
    if args.tonetwist_big_muff_nc:
        tonetwist_items = discover_tonetwist_big_muff_nc(
            args.data / "tonetwist-nc", args.tonetwist_train_repeats
        )
        for name in parts:
            parts[name].extend(tonetwist_items[name])
    source_manifest_path = ROOT / "train" / "sources.json"
    source_manifest_sha256 = hashlib.sha256(source_manifest_path.read_bytes()).hexdigest()
    remfx_manifest = None
    if args.remfx_1_1:
        remfx_manifest_path = ROOT / "train" / "runs" / "remfx-1-1-pairs.json"
        if not remfx_manifest_path.exists():
            parser.error("RemFX is excluded from the active Inspector pipeline")
        remfx_manifest_bytes = remfx_manifest_path.read_bytes()
        remfx_manifest_payload = json.loads(remfx_manifest_bytes)
        remfx_items = discover_remfx_1_1(args.data / "remfx-1-1")
        expected_items = len(remfx_manifest_payload.get("pairs", [])) * 2
        if not remfx_items or len(remfx_items) != expected_items:
            parser.error("RemFX audit manifest does not match discovered training items")
        parts["train"].extend(remfx_items)
        remfx_manifest = {
            "path": str(remfx_manifest_path.resolve()),
            "sha256": hashlib.sha256(remfx_manifest_bytes).hexdigest(),
            "record": remfx_manifest_payload["record"],
            "license": remfx_manifest_payload["license"],
            "counts": remfx_manifest_payload["counts"],
            "items": len(remfx_items),
            "policy": remfx_manifest_payload["detector_policy"],
        }
    idmt_manifest = args.idmt_manifest
    idmt = {name: [] for name in parts}
    if args.idmt_guitar:
        idmt = discover_idmt_guitar(
            args.data / "idmt-smt-audio-effects", idmt_manifest
        )
        if not any(idmt.values()):
            parser.error("IDMT is excluded from the active Inspector pipeline")
        for name in parts:
            parts[name].extend(idmt[name])
    clean_paths = {source.path.resolve() for source in clean if eligible_clean(source)}
    clean_paths.update(
        item.source.path.resolve()
        for items in chain_items.values()
        for item in items
        if guitar_effect_chain_is_clean(item.source)
    )
    clean_paths.update(
        item.source.path.resolve()
        for items in tonetwist_items.values()
        for item in items
        if item.target is not None and not any(item.target)
    )
    feature_cache_started = time.perf_counter()
    cached = {name: cache_features(items, name, args.cache, args.batch) for name, items in parts.items()}
    feature_cache_seconds = time.perf_counter() - feature_cache_started
    device = target_device()
    model = Detector(stem_stride=args.stem_stride).to(device)
    model.load_state_dict(torch.load(args.checkpoint, map_location=device, weights_only=True))
    model.eval()
    for parameter in model.parameters():
        parameter.requires_grad = False
    checkpoint_hash = checkpoint_sha256(args.checkpoint)
    # The cache filename keeps only the first twelve characters, so prefix the
    # architecture tag rather than appending it where it would be discarded.
    encoder_cache_key = f"s{args.stem_stride}-{checkpoint_hash}"
    encoding_started = time.perf_counter()
    encoded = {
        name: cached_encoding(
            model, items, cached[name], name, args.cache, encoder_cache_key, args.batch, device
        )
        for name, items in parts.items()
    }
    encoding_seconds = time.perf_counter() - encoding_started
    masks = {name: actual_clean_mask(items, clean_paths) for name, items in parts.items()}
    episode_started = time.perf_counter()
    episode = {
        name: episode_features(
            encoded[name], masks[name], args.feature_mode, args.seed + index * 10_007,
            args.train_episodes if name == "train" else 1,
        )
        for index, name in enumerate(("train", "valid", "calibrate", "test"))
    }
    episode_seconds = time.perf_counter() - episode_started
    base_dimension = representation(encoded["train"], args.feature_mode).shape[1]
    input_dimension = base_dimension * 5
    head = RelativeHead(input_dimension).to(device)
    if args.initial_head:
        head.load_state_dict(
            torch.load(args.initial_head, map_location=device, weights_only=True)
        )
        completed, best, training_seconds = 0, None, 0.0
        torch.save(head.state_dict(), args.output / "relative-head.pt")
    else:
        if args.warm_start_head:
            head.load_state_dict(
                torch.load(
                    args.warm_start_head, map_location=device, weights_only=True
                )
            )
        completed, best, training_seconds = train_head(
            head,
            (episode["train"][0], episode["train"][1]),
            (episode["valid"][0], episode["valid"][1]),
            args.output,
            device,
            args.epochs,
            args.patience,
            args.head_learning_rate,
        )
    calibrate_logits = infer(head, episode["calibrate"][0], device)
    test_logits = infer(head, episode["test"][0], device)
    scales, biases = fit_platt(episode["calibrate"][1], calibrate_logits)
    calibrate_probabilities = calibrated(calibrate_logits, scales, biases)
    threshold = thresholds(
        episode["calibrate"][1], calibrate_probabilities,
        args.calibration_clean_fp_target,
    )
    calibrate_report = metrics(episode["calibrate"][1], calibrate_probabilities, threshold)
    test_probabilities = calibrated(test_logits, scales, biases)
    pair_calibrate_report = metrics(
        episode["calibrate"][1], calibrate_probabilities, threshold
    )
    pair_test_report = metrics(episode["test"][1], test_probabilities, threshold)
    blind_values = None
    if args.blind_calibration:
        payload = json.loads(args.blind_calibration.read_text())
        blind_values_list = [
            np.asarray([payload[key][label] for label in LABELS], dtype=np.float32)
            for key in ("scale", "bias", "threshold")
        ]
        if args.blind_delay_threshold is not None:
            blind_values_list[2][1] = args.blind_delay_threshold
        blind_values = tuple(blind_values_list)

    def fused_report(name: str, pair_probabilities: np.ndarray) -> tuple[dict, np.ndarray]:
        if blind_values is None:
            return metrics(episode[name][1], pair_probabilities, threshold), pair_probabilities
        blind_scales, blind_biases, blind_threshold = blind_values
        query = episode[name][2]
        blind_probabilities = calibrated(
            encoded[name]["base_logits"][query], blind_scales, blind_biases
        )
        pair_predicted = pair_probabilities >= threshold
        blind_predicted = blind_probabilities >= blind_threshold
        fused = pair_predicted.copy()
        fused[:, 1] = (
            pair_predicted[:, 1]
            if args.delay_route == "pair"
            else blind_predicted[:, 1]
        )
        fused[:, 0] = np.logical_or(pair_predicted[:, 0], blind_predicted[:, 0])
        fused[:, 2] = (
            pair_predicted[:, 2]
            if args.reverb_route == "pair"
            else np.logical_or(pair_predicted[:, 2], blind_predicted[:, 2])
        )
        return metrics(
            episode[name][1], fused.astype(np.float32),
            np.full(len(LABELS), 0.5, dtype=np.float32),
        ), fused.astype(np.float32)

    calibrate_report, calibrate_primary = fused_report(
        "calibrate", calibrate_probabilities
    )
    test_report, test_primary = fused_report("test", test_probabilities)
    domains = encoded["test"]["domain"][episode["test"][2]].astype(str)
    domain_report = {
        domain: domain_metrics(
            episode["test"][1][domains == domain],
            test_primary[domains == domain],
            np.full(len(LABELS), 0.5, dtype=np.float32)
            if blind_values is not None else threshold,
        )
        for domain in sorted(set(domains))
    }
    external_reports = {}
    clean_profile = None
    for seconds in (5, 10, 20):
        report, profile = external_report(
            model, head, args.reference, args.external, scales, biases, seconds,
            args.feature_mode, device, blind_values, args.delay_route,
            args.reverb_route,
            args.external_delay_floor,
            args.external_reverb_floor,
        )
        external_reports[str(seconds)] = report
        if seconds == args.reference_seconds:
            clean_profile = profile
    if clean_profile is None:
        raise RuntimeError("selected clean profile was not produced")
    np.savez_compressed(args.output / "clean-profile.npz", **clean_profile)
    parity = export(model, head, input_dimension, args.output)
    calibration = {
        "scale": dict(zip(LABELS, map(float, scales))),
        "bias": dict(zip(LABELS, map(float, biases))),
        "threshold": dict(zip(LABELS, map(float, threshold))),
    }
    primary_external = external_reports[str(args.reference_seconds)]
    report = {
        "experiment": experiment,
        "hypothesis": hypothesis,
        "architecture": {
            "encoder": f"frozen compact-resnet18-16-32-64-128-stem-stride{args.stem_stride}",
            "encoder_parameters": parameters(model),
            "relative_head": f"{input_dimension}-256-64-3 MLP",
            "relative_head_parameters": parameters(head),
            "embedding": EMBEDDING,
            "physics_features": PHYSICS,
            "feature_mode": args.feature_mode,
            "fused_features": ["query", "clean-mean", "query-minus-clean", "absolute-difference", "clean-standard-deviation"],
            "user_gradient_updates": 0,
            "routing": {
                "drive": "pair/blind OR" if blind_values is not None else "pair",
                "delay": args.delay_route if blind_values is not None else "pair",
                "reverb": args.reverb_route if blind_values is not None else "pair",
                "external_delay_floor": args.external_delay_floor,
                "external_reverb_floor": args.external_reverb_floor,
                "blind_delay_threshold_override": args.blind_delay_threshold,
            },
        },
        "data_policy": {
            "source_manifest": str(source_manifest_path.resolve()),
            "source_manifest_sha256": source_manifest_sha256,
            "relative_head_positive_audio": (
                "EGFxSet real hardware plus CC-BY-4.0 DAFx25 archived chains"
                if args.guitar_effects_chains
                else "EGFxSet archived real hardware plus audited IDMT guitar effects"
                if args.idmt_guitar
                else "EGFxSet archived real hardware plus official RemFX 1-1 recordings"
                if args.remfx_1_1
                else "EGFxSet archived real hardware only"
            ),
            "backbone_checkpoint": str(args.checkpoint.resolve()),
            "backbone_effect_data": "inherited from frozen checkpoint",
            "clean_audio": "archived untreated/direct recordings only",
            "relative_head_generated_audio": False,
            "user_side_dynamic_dsp": False,
            "user_reference": str(args.reference.resolve()),
            "user_reference_seconds": args.reference_seconds,
            "external_queries": str(args.external.resolve()),
            "remfx_1_1": {
                "enabled": args.remfx_1_1,
                "manifest": remfx_manifest,
                "split": "train only" if args.remfx_1_1 else None,
                "locally_generated_audio": False,
            },
            "idmt_guitar": {
                "enabled": args.idmt_guitar,
                "manifest": str(idmt_manifest.resolve()) if args.idmt_guitar else None,
                "license": "CC-BY-NC-ND-4.0; non-commercial research only"
                if args.idmt_guitar
                else None,
                "reference_policy": (
                    "NoFX only; same device setting and different performance group"
                    if args.idmt_guitar
                    else None
                ),
                "items": {name: len(values) for name, values in idmt.items()},
            },
            "guitar_effects_chains": {
                "enabled": args.guitar_effects_chains,
                "record": "https://zenodo.org/records/7871720"
                if args.guitar_effects_chains
                else None,
                "license": "CC-BY-4.0" if args.guitar_effects_chains else None,
                "items": {name: len(items) for name, items in chain_items.items()},
                "split_policy": "PRS+Les Paul train; Strat validation/calibration; Telecaster test",
            },
            "tonetwist_big_muff_nc": {
                "enabled": args.tonetwist_big_muff_nc,
                "license": "CC-BY-NC-4.0; non-commercial research only"
                if args.tonetwist_big_muff_nc
                else None,
                "records": [
                    "https://zenodo.org/records/10797916",
                    "https://zenodo.org/records/10891515",
                ]
                if args.tonetwist_big_muff_nc
                else [],
                "items": {
                    name: len(items) for name, items in tonetwist_items.items()
                },
                "split_policy": "DIY train only; published EHX train/validation/test preserved",
            },
            "aachen_rir": {
                "enabled": args.aachen_rir,
                "record": "https://zenodo.org/records/20428705"
                if args.aachen_rir
                else None,
                "license": "CC-BY-4.0" if args.aachen_rir else None,
                "render_policy": "ephemeral measured-RIR convolution; no derived audio corpus stored"
                if args.aachen_rir
                else None,
            },
        },
        "split": {name: len(items) for name, items in parts.items()},
        "split_domains": {
            name: {
                domain: sum(item.source.domain == domain for item in items)
                for domain in sorted({item.source.domain for item in items})
            }
            for name, items in parts.items()
        },
        "episode_audit": {name: episode[name][3] for name in episode},
        "training": {
            "device": str(device),
            "encoder_checkpoint": str(args.checkpoint.resolve()),
            "encoder_checkpoint_sha256": checkpoint_hash,
            "feature_cache_seconds": feature_cache_seconds,
            "encoding_seconds": encoding_seconds,
            "episode_build_seconds": episode_seconds,
            "head_epochs": completed,
            "best_validation_loss": best,
            "head_training_seconds": training_seconds,
            "head_learning_rate": args.head_learning_rate,
            "initial_head": str(args.initial_head.resolve()) if args.initial_head else None,
            "warm_start_head": (
                str(args.warm_start_head.resolve()) if args.warm_start_head else None
            ),
            "calibration_clean_fp_target": args.calibration_clean_fp_target,
        },
        "calibration": calibration,
        "calibrate": calibrate_report,
        "pair_calibrate": pair_calibrate_report,
        "calibration_gate_feasibility": gate_feasibility(episode["calibrate"][1], calibrate_probabilities),
        "test": test_report,
        "pair_test": pair_test_report,
        "test_domains": domain_report,
        "external_reference_duration_ablation": external_reports,
        "quality_gate": quality_gate(
            calibrate_report, test_report, domain_report, primary_external
        ),
        "export_parity": parity,
        "limitations": [
            "the external directory is development evidence and is too small for a final hardware claim",
            "the external directory has no independent unambiguous Clean query after clean.wav is used as reference",
            f"this experiment tests {args.feature_mode} relative features without changing the frozen encoder",
        ]
        + (
            ["RemFX is CC-NC and restricts this run to non-commercial research"]
            if args.remfx_1_1
            else []
        )
        + (
            [
                "the label-specific fusion rule was selected on the external development directory and requires a new held-out hardware test"
            ]
            if blind_values is not None
            else []
        ),
    }
    (args.output / "metrics.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    (args.output / "calibration.json").write_text(json.dumps(calibration, indent=2, sort_keys=True) + "\n")
    json.dump(report, sys.stdout, indent=2, sort_keys=True)
    print()


if __name__ == "__main__":
    main()
